#!/usr/bin/env python3
"""Take apart someone's profile README so its style can be rebuilt for another person.

  python3 inspect_profile.py LOGIN          # user profile: LOGIN/LOGIN, README.md
  python3 inspect_profile.py ORG --org      # organisation profile: ORG/.github, profile/README.md

Prints the licence (what may be reused), layout features, every image with the
component it most likely is and how it is produced (live third-party service,
generated into the repo by a workflow, or a static file), the workflows and the
actions they use, and the repo's own asset files. Public data only, via `gh`.
"""
import argparse
import base64
import json
import re
import subprocess

# (url fragment, what it is, how it is produced) - first match wins.
COMPONENTS = [
    ("github-readme-stats", "stats / top-languages / repo pin card (anuraghazra/github-readme-stats)", "service"),
    ("streak-stats", "contribution streak (DenverCoder1/github-readme-streak-stats)", "service"),
    ("readme-typing-svg", "typing-animation header (DenverCoder1/readme-typing-svg)", "service"),
    ("capsule-render", "wave / banner header (kyechan99/capsule-render)", "service"),
    ("skillicons.dev", "tech-stack icons (tandpfun/skill-icons)", "service"),
    ("img.shields.io", "shields.io badge", "service"),
    ("github-profile-trophy", "trophies (ryo-ma/github-profile-trophy)", "service"),
    ("activity-graph", "contribution activity graph (github-readme-activity-graph)", "service"),
    ("komarev.com/ghpvc", "profile view counter", "service"),
    ("visitor-badge", "visitor counter", "service"),
    ("spotify", "Spotify now-playing card", "service"),
    ("wakatime", "WakaTime coding stats", "service"),
    ("github-profile-3d-contrib", "3D contribution calendar (yoshi389111/github-profile-3d-contrib)", "action"),
    ("snake", "contribution-graph snake (Platane/snk)", "action"),
    ("metrics", "metrics infographic (lowlighter/metrics)", "action"),
    ("user-attachments", "image uploaded to GitHub", "static"),
    ("giphy", "GIF from Giphy", "service"),
]


def gh(*args):
    r = subprocess.run(["gh", "api", *args], capture_output=True, text=True)
    return json.loads(r.stdout) if r.returncode == 0 and r.stdout.strip() else None


def classify(url, generated):
    for frag, what, how in COMPONENTS:
        if frag in url:
            return what, how
    if not url.startswith("http") or f"/raw/" in url or "raw.githubusercontent" in url:
        return "file in the profile repo", "generated by a workflow" if generated else "static file"
    return "external image", "service or static"


def structure(md):
    feats = {
        "lines": md.count("\n") + 1,
        "headings": len(re.findall(r"^#{1,6} ", md, re.M)) + len(re.findall(r"<h[1-6]", md, re.I)),
        "markdown tables": len(re.findall(r"^\|?\s*:?-{3,}", md, re.M)),
        "html tables": len(re.findall(r"<table", md, re.I)),
        "collapsible <details>": len(re.findall(r"<details", md, re.I)),
        "centred blocks": len(re.findall(r'align=["\']?center', md, re.I)),
        "theme-aware <picture>": len(re.findall(r"prefers-color-scheme", md)),
        "#gh-dark/light-mode-only images": len(re.findall(r"#gh-(dark|light)-mode-only", md)),
        "comment markers (auto-updated sections)": len(re.findall(r"<!--\s*[A-Z_-]+:\s*START", md)),
        "emoji": len(re.findall("[\U0001F300-\U0001FAFF☀-➿]", md)),
    }
    return {k: v for k, v in feats.items() if v}


def images(md):
    """Image URLs in document order, Markdown and HTML alike."""
    pat = re.compile(r"!\[[^\]]*\]\(([^)\s]+)|(?:src|srcset)=[\"']([^\"']+)", re.I)
    return list(dict.fromkeys((m.group(1) or m.group(2)).split(" ")[0] for m in pat.finditer(md)))


def selfcheck():
    assert classify("https://github-readme-stats.vercel.app/api?username=x", False)[1] == "service"
    assert classify("dark_mode.svg", True) == ("file in the profile repo", "generated by a workflow")
    assert classify("dist/snake-dark.svg", True)[1] == "action"  # a local snake file is still the snake
    assert classify("https://raw.githubusercontent.com/a/a/output/github-contribution-grid-snake.svg", True)[1] == "action"
    assert images('<img src="a.svg"> ![x](b.png "t")') == ["a.svg", "b.png"]


if __name__ == "__main__":
    selfcheck()
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("login")
    ap.add_argument("--org", action="store_true")
    a = ap.parse_args()
    repo, path = (f"{a.login}/.github", "profile/README.md") if a.org else (f"{a.login}/{a.login}", "README.md")
    meta = gh(f"repos/{repo}")
    if not meta:
        raise SystemExit(f"{repo} not found or not public")
    doc = gh(f"repos/{repo}/contents/{path}")
    if not doc:
        raise SystemExit(f"{repo} has no {path}")
    md = base64.b64decode(doc["content"]).decode("utf-8", "replace")
    lic = (meta.get("license") or {}).get("spdx_id") or "none"
    print(f"== {repo}/{path}  (stars {meta['stargazers_count']}, licence {lic})")
    if lic in ("none", "NOASSERTION"):
        print("   no licence: rebuild the layout and ideas with your own code; copy no code, images or text")
    else:
        print(f"   {lic}: code may be reused under its terms (keep the notice); never copy personal content")
    print("\n-- layout")
    for k, v in structure(md).items():
        print(f"   {k}: {v}")
    flows = gh(f"repos/{repo}/contents/.github/workflows") or []
    actions = []
    print("\n-- workflows")
    for f in flows if isinstance(flows, list) else []:
        body = gh(f"repos/{repo}/contents/{f['path']}") or {}
        text = base64.b64decode(body.get("content", "")).decode("utf-8", "replace")
        uses = sorted(set(re.findall(r"uses:\s*['\"]?([^\s@'\"]+)", text)))
        crons = re.findall(r"cron:\s*['\"]?([^'\"\n]+)", text)
        actions += uses
        print(f"   {f['name']}: schedule {crons or '-'}; uses {', '.join(uses) or '-'}")
    if not flows:
        print("   none")
    print("\n-- images")
    for u in images(md):
        what, how = classify(u, bool(flows))
        print(f"   [{how}] {what}\n        {u[:140]}")
    tree = gh(f"repos/{repo}/git/trees/HEAD?recursive=1") or {"tree": []}
    assets = [t for t in tree["tree"] if t["type"] == "blob" and re.search(r"\.(svg|gif|png|jpe?g|py|js|ts|json|ya?ml)$", t["path"])]
    print("\n-- repo files")
    for t in assets[:40]:
        print(f"   {t.get('size', 0):>8}  {t['path']}")
    print("\nlook next: the live page (github.com/%s) for how it renders, the workflows above for how it updates" % a.login)
